del *.mat2dpts
del *.grid2dpts
del *.mat3dpts
del *.grid3dpts
del *.matcolors
del *.gridcolors
del *.data
del *.stats
del *.points
del *.colors
del *.links
del *.fixedMap
del *.grayValueMap
del *.correspondenceMap
del *.disjointSetMap
del *.nVisitedMap
del *.evtMap
del *.distanceMap
del *.nodeParentMap

